/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dk_itu_alphatrainer_signalprocessing_OpenCVSignalProcessor */

#ifndef _Included_dk_itu_alphatrainer_signalprocessing_OpenCVSignalProcessor
#define _Included_dk_itu_alphatrainer_signalprocessing_OpenCVSignalProcessor
#ifdef __cplusplus
extern "C" {
#endif
#undef dk_itu_alphatrainer_signalprocessing_OpenCVSignalProcessor_lowCutFq
#define dk_itu_alphatrainer_signalprocessing_OpenCVSignalProcessor_lowCutFq 5.0f
#undef dk_itu_alphatrainer_signalprocessing_OpenCVSignalProcessor_hiCutFq
#define dk_itu_alphatrainer_signalprocessing_OpenCVSignalProcessor_hiCutFq 50.0f
/*
 * Class:     dk_itu_alphatrainer_signalprocessing_OpenCVSignalProcessor
 * Method:    getBrainProcessed
 * Signature: ([FIIIFFF)F
 */
JNIEXPORT jfloat JNICALL Java_dk_itu_alphatrainer_signalprocessing_OpenCVSignalProcessor_getBrainProcessed
  (JNIEnv *, jobject, jfloatArray, jint, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     dk_itu_alphatrainer_signalprocessing_OpenCVSignalProcessor
 * Method:    getMinMaxProcessed
 * Signature: ([FII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_dk_itu_alphatrainer_signalprocessing_OpenCVSignalProcessor_getMinMaxProcessed
  (JNIEnv *, jobject, jfloatArray, jint, jint);

/*
 * Class:     dk_itu_alphatrainer_signalprocessing_OpenCVSignalProcessor
 * Method:    getAlphaPeak
 * Signature: ([FIII)F
 */
JNIEXPORT jfloat JNICALL Java_dk_itu_alphatrainer_signalprocessing_OpenCVSignalProcessor_getAlphaPeak
  (JNIEnv *, jobject, jfloatArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
